name: {{ cookiecutter.repo_name }}
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - catboost
  - dvc
  - flake8
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python-dotenv>=0.5.1
  - scikit-learn
  - seaborn
  - Sphinx
  - statsmodels
